# Generated by Django 6.0.2 on 2026-02-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
