# Generated by Django 6.0.3 on 2026-07-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_card_otp_alter_card_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_delivery_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
