# Generated by Django 6.0.2 on 2026-02-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='notifications',
        ),
    ]
