# Generated by Django 6.0.3 on 2026-08-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='language',
        ),
    ]
