# Generated by Django 6.0.3 on 2026-08-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_usersettings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_warehouse_staff",
            field=models.BooleanField(default=False),
        ),
    ]
