# Generated by Django 6.0.3 on 2026-09-26 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant_interface', '0012_membership_wallet_balance'),
        ('orders', '0012_remove_cart_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('finished', 'Finished'), ('expired', 'Expired'), ('released', 'Released')], default='claimed', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_processed', models.PositiveIntegerField(blank=True, null=True)),
                ('wage_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_claims', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='merchant_interface.membership')),
                ('store_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='orders.storeorder')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transaction', to='fulfillment.orderclaim')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='merchant_interface.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'claimed')), fields=('store_order',), name='one_active_claim_per_store_order'),
        ),
    ]
