# Generated by Django 6.0.2 on 2026-02-23 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('inauguration_date', models.DateField(auto_now_add=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='store_pics/')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant_interface.niche')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('Owner', 'owner'), ('Helper', 'helper'), ('Manager', 'manager')], default='helper', max_length=7)),
                ('wage_type', models.CharField(choices=[('Salary', 'salary'), ('Percentage', 'percentage')], default='helper', max_length=10)),
                ('wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_interface.store')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedNiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('suggestion_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'owner'), ('Helper', 'helper'), ('Manager', 'manager')], default='helper', max_length=7)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('wage_type', models.CharField(choices=[('Salary', 'salary'), ('Percentage', 'percentage')], default='helper', max_length=10)),
                ('wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_interface.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='unique_membership_per_store')],
            },
        ),
    ]
