# Generated by Django 6.0.2 on 2026-02-19 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_interface', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_interface.store'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='inaguration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
