# Generated by Django 6.0.3 on 2026-07-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_interface', '0002_alter_membership_role_alter_membership_wage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipinvitation',
            name='status',
            field=models.CharField(choices=[('Accepted', 'accepted'), ('Rejected', 'rejected'), ('Pending', 'pending')], default='Pending', max_length=10),
        ),
    ]
