# Generated by Django 6.0.3 on 2026-08-24 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_interface", "0003_membershipinvitation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={"ordering": ["join_date"]},
        ),
        migrations.AlterModelOptions(
            name="membershipinvitation",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AlterModelOptions(
            name="niche",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ["-inauguration_date"]},
        ),
        migrations.AlterModelOptions(
            name="suggestedniche",
            options={"ordering": ["-suggestion_time"]},
        ),
        migrations.RenameField(
            model_name="store",
            old_name="picture",
            new_name="cover_picture",
        ),
        migrations.AddField(
            model_name="membershipinvitation",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="main_picture",
            field=models.ImageField(blank=True, null=True, upload_to="store_pics/"),
        ),
        migrations.AddField(
            model_name="suggestedniche",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("helper", "Helper"),
                    ("manager", "Manager"),
                ],
                default="helper",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="wage_type",
            field=models.CharField(
                choices=[("salary", "Salary"), ("percentage", "Percentage")],
                default="salary",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="membershipinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("helper", "Helper"),
                    ("manager", "Manager"),
                ],
                default="helper",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="membershipinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="membershipinvitation",
            name="wage_type",
            field=models.CharField(
                choices=[("salary", "Salary"), ("percentage", "Percentage")],
                default="salary",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("wage_type", "salary"),
                    models.Q(("wage__lte", 100), ("wage_type", "percentage")),
                    _connector="OR",
                ),
                name="percentage_wage_capped_at_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("store", "invitee_email"),
                name="one_pending_invite_per_email_per_store",
            ),
        ),
    ]
