# Generated by Django 6.0.3 on 2026-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_interface", "0005_membershipchangerequest_promotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="new_position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="old_position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
