# Generated by Django 6.0.3 on 2026-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_interface", "0006_alter_promotion_new_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="new_wage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="new_wage_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="promotion",
            name="old_wage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="old_wage_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="suggestedniche",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
