# Generated by Django 6.0.3 on 2026-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_interface", "0008_alter_membership_wage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
