# Generated by Django 6.0.3 on 2026-08-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_interface", "0009_store_description_store_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_membership_per_store",
        ),
        migrations.RemoveConstraint(
            model_name="membership",
            name="percentage_wage_capped_at_100",
        ),
        migrations.RemoveConstraint(
            model_name="membership",
            name="membership_wage_not_negative",
        ),
    ]
