# Generated by Django 6.0.3 on 2026-08-31 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_interface", "0010_alter_membership_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={"ordering": ["join_date"]},
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "store"), name="unique_membership_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("wage_type", "salary"),
                    models.Q(("wage__lte", 100), ("wage_type", "percentage")),
                    _connector="OR",
                ),
                name="percentage_wage_capped_at_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("wage__isnull", True), ("wage__gte", 0), _connector="OR"
                ),
                name="membership_wage_not_negative",
            ),
        ),
    ]
