# Generated by Django 6.0.3 on 2026-09-26 09:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_interface', '0011_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
