# Generated by Django 6.0.3 on 2026-08-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
    ]
