# Generated by Django 6.0.3 on 2026-08-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_order_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                blank=True, choices=[("cash", "Cash")], max_length=4, null=True
            ),
        ),
    ]
